
/*
    Copyright 2000  Li-Cheng (Andy) Tai

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>

#include "ui.h"
#include "support.h"
#include "util.h"

int
main (int argc, char *argv[])
{
  /*GtkWidget *about;
  GtkWidget *new_canvas_window; */

#ifdef ENABLE_NLS
   bindtextdomain (PACKAGE, PACKAGE_LOCALE_DIR);
   textdomain (PACKAGE); 

#endif

   gnome_init ("GNU Paint", VERSION, argc, argv);
   gdk_rgb_init();
/* use default visual and colormap from GdkRGB */
   gtk_widget_set_default_colormap (gdk_rgb_get_cmap());
   gtk_widget_set_default_visual (gdk_rgb_get_visual());
   
   
   busy_cursor = gdk_cursor_new(GDK_WATCH); 
   
   arrow_cursor = gdk_cursor_new(GDK_LEFT_PTR); 
  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
   create_image_buf(0, DEFAULT_WIDTH, DEFAULT_HEIGHT);
   gtk_main ();
   return 0;
}

